# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:34
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    replaces = [(b'memo', '0001_initial'), (b'memo', '0002_userprofile_daily_words_amount'), (b'memo', '0003_auto_20160510_1719'), (b'memo', '0004_vocabulary_description'), (b'memo', '0005_word_example'), (b'memo', '0006_auto_20160510_1815'), (b'memo', '0007_auto_20160510_1831'), (b'memo', '0008_auto_20160510_1933')]

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Memo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(verbose_name='Content')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Vocabulary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Name')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=100, verbose_name='Content')),
                ('description', models.TextField(verbose_name='Description')),
                ('vocabulary', models.ManyToManyField(default='', to=b'memo.Vocabulary')),
                ('example', models.TextField(default='', verbose_name='Example Sentence')),
            ],
        ),
        migrations.AddField(
            model_name='userprofile',
            name='current_vocabulary',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='memo.Vocabulary'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='memorized_words',
            field=models.ManyToManyField(blank=True, to=b'memo.Word'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='memo',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.Word'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='daily_words_amount',
            field=models.SmallIntegerField(default=20, verbose_name='Daily Words Amount'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AddField(
            model_name='vocabulary',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.CreateModel(
            name='LearningWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.Word')),
            ],
        ),
    ]
