# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_squashed_0008_auto_20160510_1933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='vocabulary',
            field=models.ManyToManyField(to='memo.Vocabulary'),
        ),
    ]
