# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 09:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='daily_words_amount',
            field=models.SmallIntegerField(default=100, verbose_name='Daily Words Amount'),
        ),
    ]
