# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0002_auto_20160510_1948'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='learningword',
            name='user',
        ),
        migrations.RemoveField(
            model_name='learningword',
            name='word',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='learning_words',
            field=models.ManyToManyField(blank=True, related_name='learning', to='memo.Word'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='memorized_words',
            field=models.ManyToManyField(blank=True, related_name='memorized_words', to='memo.Word'),
        ),
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Content'),
        ),
        migrations.DeleteModel(
            name='LearningWord',
        ),
    ]
