# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20160510_1719'),
    ]

    operations = [
        migrations.AddField(
            model_name='vocabulary',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
            preserve_default=False,
        ),
    ]
