# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 15:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0003_auto_20160510_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='word',
            name='content',
            field=models.CharField(max_length=100, verbose_name='Content'),
        ),
    ]
