# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 09:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0004_vocabulary_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='word',
            name='example',
            field=models.TextField(default='', verbose_name='Example Sentence'),
            preserve_default=False,
        ),
    ]
