# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 23:23
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo', '0005_auto_20160510_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.Word')),
            ],
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='learning_words',
        ),
    ]
