# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 10:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0005_word_example'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memo',
            name='content',
            field=models.TextField(default='', verbose_name='Content'),
        ),
        migrations.AlterField(
            model_name='vocabulary',
            name='description',
            field=models.TextField(default='', verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='word',
            name='example',
            field=models.TextField(default='', verbose_name='Example Sentence'),
        ),
        migrations.AlterField(
            model_name='word',
            name='vocabulary',
            field=models.ManyToManyField(default='', to='memo.Vocabulary'),
        ),
    ]
