# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-10 11:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('memo', '0007_auto_20160510_1831'),
    ]

    operations = [
        migrations.CreateModel(
            name='LearningWord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('word', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='memo.Word')),
            ],
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='daily_words_amount',
            field=models.SmallIntegerField(default=20, verbose_name='Daily Words Amount'),
        ),
    ]
