# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-12 08:09
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0008_learningword_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 5, 12, 16, 9, 30, 774000), verbose_name='Publish time'),
        ),
    ]
