# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 08:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0010_auto_20160512_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Publish time'),
        ),
    ]
