# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-14 19:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('memo', '0011_auto_20160513_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='current_vocabulary',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='memo.Vocabulary'),
        ),
    ]
